name: msgpack_dart
description: Message Pack implementation for dart
version: 0.0.7
author: Matej Knopp <matej.knopp@gmail.com>
homepage: https://github.com/knopp/msgpack_dart

environment:
    sdk: ">=2.0.0-dev.68.0 <3.0.0"

dev_dependencies:
    test: ^1.3.0
