name: algorand_msgpack
description: Unofficial community SDK to interact with the Algorand network, for Dart & Flutter
version: 1.0.1
homepage: https://www.algorand.com
repository: https://github.com/RootSoft/msgpack_dart.git
issue_tracker: https://github.com/RootSoft/msgpack_dart.git/issues

environment:
    sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
    test: ^1.3.0
