name: msgpack_dart
description: Dart package for simple and easy MessagePack binary serialization
version: 1.0.1
author: Matej Knopp <matej.knopp@gmail.com>
homepage: https://github.com/knopp/msgpack_dart

environment:
    sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
    test: ^1.3.0
